version: 2.1
orbs:
  devops-tactile-package-orb: tactilegames/devops-tactile-package-orb@volatile

all-cheats: &all-cheats [
  'TACTILE_CHEATS',
  'TACTILE_NO_CHEATS',
]

all-unity-versions: &all-unity-versions [
   2022,6000
]

workflows:
  version: 2.1
  verify-development-commit:
    jobs:
      - custom-step 
      - devops-tactile-package-orb/commit-validation-ios:
          platform: "ios"
          requires:
            - custom-step
          context:
            - CLIENT_PACKAGES
          matrix:
            parameters:
              cheats: *all-cheats
              unity-version: *all-unity-versions
      - devops-tactile-package-orb/commit-validation-android:
          platform: "android"
          requires:
            - custom-step
          context:
            - CLIENT_PACKAGES
          matrix:
            parameters:
              cheats: *all-cheats
              unity-version: *all-unity-versions
      - devops-tactile-package-orb/publish-package:
          context:
            - CLIENT_PACKAGES
          requires:
            - devops-tactile-package-orb/commit-validation-ios
            - devops-tactile-package-orb/commit-validation-android
            - custom-step
          filters:
            branches:
              only: ["master"]
            
jobs:
  custom-step:
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      - run:
          name: Run custom script if any
          command: |
            if [ -f ".circleci/custom-step" ]; then
              chmod +x .circleci/custom-step
              echo "Custom step exists, running script..."
              ./.circleci/custom-step
            else
              echo "No custom step. Skipping..."
            fi
