using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Rosalina.Generator {

	public class CodeGenerator {

		private int indentation;
		
		internal RosalinaGenerationResult Generate(UIDocumentAsset uiDocumentAsset, string outputPath) {
			if (uiDocumentAsset is null) {
				throw new ArgumentNullException(nameof(uiDocumentAsset),
					"Cannot generate binding with an empty UI document definition.");
			}

			if (string.IsNullOrEmpty(outputPath)) {
				throw new ArgumentException("An output file name is required.", nameof(outputPath));
			}
			
			var uxml = RosalinaUXMLParser.ParseUIDocument(uiDocumentAsset.FullPath);
			if (!uxml.RootNode.GenerateCodeBehind) {
				return new RosalinaGenerationResult(null, null);
			}

			return new RosalinaGenerationResult(GenerateCode(uxml), CreateOutputFilePath(uiDocumentAsset, outputPath));
		}

		private string GenerateCode(UxmlDocument uxml) {
			return @$"//AUTO-GENERATED by com.tactilegames.uielements-code-behind
{GetImports(uxml)}

{GetNamespaceStart(uxml)}

{GetClassStart(uxml)}

{GenerateProperties(uxml)}

{GenerateBindingsMethod(uxml)}

{GetClassEnd(uxml)}

{GetNamespaceEnd(uxml)}
";
		}

		private StringBuilder GetImports(UxmlDocument uxml) {
			var stringBuilder = new StringBuilder();
			foreach (var @namespace in uxml.GetChildren().Select(node => node.Namespace).Distinct()) {
				stringBuilder.AppendLine($"using {@namespace};");
			}

			return stringBuilder;
		}

		private string GetNamespaceStart(UxmlDocument uxmlDocument) {
			if (string.IsNullOrWhiteSpace(uxmlDocument.RootNode.Namespace)) {
				return "";
			}

			indentation++;
			return $"namespace {uxmlDocument.RootNode.Namespace}{{";
		}

		
		private string GetClassStart(UxmlDocument uxml) {
			var name = Path.GetFileNameWithoutExtension(uxml.Name);
			var classStart = $"{DoIndent()}public partial class {name} {{";
			indentation++;
			return classStart;
		}

		private StringBuilder GenerateProperties(UxmlDocument uxml) {
			var stringBuilder = new StringBuilder();
			stringBuilder.Append(@$"{DoIndent()}public VisualElement RootVisualElement {{get; private set;}}");
			stringBuilder.AppendLine();
			stringBuilder.AppendLine();
			IEnumerable<UIProperty> properties = uxml.GetChildren().Select(x => new UIProperty(x.Type, x.Name)).ToList();

			foreach (var property in properties) {
				stringBuilder.AppendLine($"{DoIndent()}public {property.TypeName} {property.Name} {{get; private set;}}");
			}

			return stringBuilder;
		}
		
		private StringBuilder GenerateBindingsMethod(UxmlDocument uxml) {
			var stringBuilder = new StringBuilder();

			stringBuilder.AppendLine($"{DoIndent()}public void InitializeBindings(VisualElement rootVisualElement) {{");
			indentation++;

			stringBuilder.AppendLine($"{DoIndent()}RootVisualElement = rootVisualElement;");

			stringBuilder.AppendLine();

			IEnumerable<UIProperty> properties = uxml.GetChildren().Select(x => new UIProperty(x.Type, x.Name)).ToList();
			foreach (var property in properties) {
				stringBuilder.AppendLine($"{DoIndent()}{property.Name} = RootVisualElement.Q<{property.TypeName}>(\"{property.Name}\");");	
			}
			
			indentation--;
			stringBuilder.Append($"{DoIndent()}}}");
			
			return stringBuilder;
		}

		private string GenerateBindings(UxmlDocument uxml) {
			return "";
		}
		
		private string GetClassEnd(UxmlDocument uxml) {
			indentation--;
			return $"{DoIndent()}}}";
		}

		private string GetNamespaceEnd(UxmlDocument uxmlDocument) {
			if (string.IsNullOrWhiteSpace(uxmlDocument.RootNode.Namespace)) {
				return "";
			}

			indentation--;
			return "}";
		}
		
		private static string CreateOutputFilePath(UIDocumentAsset uiDocumentAsset, string outputPath) {
			return Path.Combine(uiDocumentAsset.Path, outputPath);
		}

		private string DoIndent() {
			var stringBuilder = new StringBuilder();
			for (int i = 0; i < indentation; i++) {
				stringBuilder.Append("\t");
			}

			return stringBuilder.ToString();
		}
	}

}